// Generated by schema-fetch command
// DO NOT EDIT - This file is auto-generated from Directus schema
// Generated at: 2025-11-06T19:16:39.357Z

import { createDirectus, rest, staticToken, readItems, readItem, readSingleton } from '@directus/sdk';

// Directus system types (simplified)
type Directus_users = string;
type Directus_files = string;

export interface Accomplishments {
  id?: number;
  status?: string;
  sort?: number | null;
  user_created?: Directus_users | null;
  date_created?: string | null;
  user_updated?: Directus_users | null;
  date_updated?: string | null;
  primary_title: string;
  is_featured?: boolean | null;
  primary_description: string;
  impact_metrics?: string | null;
  accomplishment_type?: string | null;
  date_achieved?: string | null;
  evidence_links?: any | null;
  position?: Positions | null;
  approximate_date?: string | null;
  accomplishment_variations?: unknown | null;
  related_technologies?: unknown | null;
  related_projects?: unknown | null;
  related_skills?: unknown | null;
  education?: unknown | null;
}

export interface Accomplishments_projects {
  id?: number;
  accomplishments_id?: Accomplishments[];
  projects_id?: Projects[];
  sort?: number | null;
}

export interface Accomplishments_skills {
  id?: number;
  accomplishments_id?: Accomplishments[];
  skills_id?: Skills[];
  sort?: number | null;
}

export interface Accomplishments_technologies {
  id?: number;
  accomplishments_id?: Accomplishments[];
  technologies_id?: Technologies[];
}

export interface Accomplishment_variations {
  id?: number;
  status?: string;
  sort?: number | null;
  user_created?: Directus_users | null;
  date_created?: string | null;
  user_updated?: Directus_users | null;
  date_updated?: string | null;
  title: string;
  is_primary?: boolean | null;
  description: string;
  context?: string | null;
  tone?: string | null;
  accomplishment?: Accomplishments | null;
}

export interface Certifications {
  id?: number;
  status?: string;
  sort?: number | null;
  user_created?: Directus_users | null;
  date_created?: string | null;
  user_updated?: Directus_users | null;
  date_updated?: string | null;
  name: string;
  issuing_organization?: string | null;
  issue_date?: string | null;
  is_active?: boolean | null;
}

export interface Companies {
  id?: number;
  status?: string;
  sort?: number | null;
  user_created?: Directus_users | null;
  date_created?: string | null;
  user_updated?: Directus_users | null;
  date_updated?: string | null;
  name: string;
  industry?: string | null;
  size?: string | null;
  location?: string | null;
  website?: string | null;
  description?: string | null;
  logo?: Directus_files | null;
  positions?: unknown | null;
  projects?: unknown | null;
}

export interface Core_values {
  id?: number;
  status?: string;
  sort?: number | null;
  user_created?: Directus_users | null;
  date_created?: string | null;
  user_updated?: Directus_users | null;
  date_updated?: string | null;
  title?: string | null;
  summary?: string | null;
  description?: string | null;
}

export interface Cover_letters {
  id?: number;
  status?: string;
  sort?: number | null;
  user_created?: Directus_users | null;
  date_created?: string | null;
  user_updated?: Directus_users | null;
  date_updated?: string | null;
  parent_cover_letter?: Cover_letters | null;
  cover_letters?: unknown | null;
  job_applications?: unknown | null;
}

export interface Education {
  id?: number;
  status?: string;
  sort?: number | null;
  user_created?: Directus_users | null;
  date_created?: string | null;
  user_updated?: Directus_users | null;
  date_updated?: string | null;
  institution: string;
  degree_type?: string | null;
  field_of_study?: string | null;
  graduation_date?: string | null;
  start_date?: string | null;
  summary?: string | null;
  description?: string | null;
  accomplishments?: unknown | null;
  related_items?: unknown | null;
}

export interface Education_accomplishments {
  id?: number;
  education_id?: Education[];
  accomplishments_id?: Accomplishments[];
}

export interface Education_related_items {
  id?: number;
  education_id?: Education[];
  item?: string | null;
  sort?: number | null;
  collection?: string | null;
}

export interface Footnotes {
  id?: number;
  status?: string;
  sort?: number | null;
  user_created?: Directus_users | null;
  date_created?: string | null;
  user_updated?: Directus_users | null;
  date_updated?: string | null;
  title?: string | null;
  description?: string | null;
}

export interface Identity {
  id?: number;
  status?: string;
  sort?: number | null;
  user_created?: Directus_users | null;
  date_created?: string | null;
  user_updated?: Directus_users | null;
  date_updated?: string | null;
  first_name: string;
  last_name: string;
  email: string;
  phone?: string | null;
  linkedin_url?: string | null;
  website_url?: string | null;
  github_url?: string | null;
  location?: string | null;
  tagline?: string | null;
  profile_photo?: Directus_files | null;
}

export interface Job_applications {
  id?: number;
  status?: string;
  sort?: number | null;
  user_created?: Directus_users | null;
  date_created?: string | null;
  user_updated?: Directus_users | null;
  date_updated?: string | null;
  company_name: string;
  position_title: string;
  job_description?: string | null;
  application_date?: string | null;
  application_status?: string | null;
  resume_used?: Resumes | null;
  cover_letter_used_?: Cover_letters | null;
}

export interface Master_resume_system_docs {
  id?: number;
  status?: string;
  sort?: number | null;
  user_created?: Directus_users | null;
  date_created?: string | null;
  user_updated?: Directus_users | null;
  date_updated?: string | null;
  title: string;
  artifact_type?: string | null;
  content?: string | null;
  conversation_date?: string | null;
  conversation_context?: string | null;
  version?: string | null;
  tags?: any | null;
  related_collections?: any | null;
  key_decisions?: string | null;
  next_steps?: string | null;
  participants?: string | null;
  artifact_source?: string | null;
  implementation_notes?: string | null;
}

export interface Positions {
  id?: number;
  status?: string;
  sort?: number | null;
  user_created?: Directus_users | null;
  date_created?: string | null;
  user_updated?: Directus_users | null;
  date_updated?: string | null;
  primary_title: string;
  department?: string | null;
  start_date?: string | null;
  end_date?: string | null;
  is_current?: boolean | null;
  employment_type?: string | null;
  description?: string | null;
  company?: Companies | null;
  summary?: string | null;
  work_location?: any | null;
  projects?: unknown | null;
  accomplishments?: unknown | null;
}

export interface Professional_summaries {
  id?: number;
  status?: string;
  sort?: number | null;
  user_created?: Directus_users | null;
  date_created?: string | null;
  user_updated?: Directus_users | null;
  date_updated?: string | null;
  title: string;
  is_default?: boolean | null;
  content: string;
  target_industry?: string | null;
  target_role_type?: string | null;
  summary?: string | null;
}

export interface Projects {
  id?: number;
  status?: string;
  sort?: number | null;
  user_created?: Directus_users | null;
  date_created?: string | null;
  user_updated?: Directus_users | null;
  date_updated?: string | null;
  name: string;
  is_featured?: boolean | null;
  description: string;
  role?: string | null;
  project_type?: string | null;
  start_date?: string | null;
  end_date?: string | null;
  project_url?: string | null;
  github_url?: string | null;
  summary?: string | null;
  // Mark this project as currently active/in progress
  current_project?: boolean | null;
  accomplishments?: unknown | null;
  skills_demonstrated?: unknown | null;
  technologies_used?: unknown | null;
  related_positions?: unknown | null;
  related_companies?: unknown | null;
  related_media?: unknown | null;
}

export interface Projects_companies {
  id?: number;
  projects_id?: Projects[];
  companies_id?: Companies[];
  sort?: number | null;
}

export interface Projects_files {
  id?: number;
  projects_id?: Projects[];
  directus_files_id?: Directus_files[];
  sort?: number | null;
}

export interface Projects_positions {
  id?: number;
  projects_id?: Projects[];
  positions_id?: Positions[];
  sort?: number | null;
}

export interface Projects_skills {
  id?: number;
  projects_id?: Projects[];
  skills_id?: Skills[];
  sort?: number | null;
}

export interface Projects_technologies {
  id?: number;
  projects_id?: Projects[];
  technologies_id?: Technologies[];
  sort?: number | null;
}

export interface Resumes {
  id?: number;
  status?: string;
  sort?: number | null;
  user_created?: Directus_users | null;
  date_created?: string | null;
  user_updated?: Directus_users | null;
  date_updated?: string | null;
  title: string;
  content: string;
  target_role?: string | null;
  target_company?: string | null;
  version_number?: number | null;
  generated_by_ai?: boolean | null;
  ai_prompt?: string | null;
  parent_resume?: Resumes | null;
  resumes?: unknown | null;
  job_applications?: unknown | null;
}

export interface Skills {
  id?: number;
  status?: string;
  sort?: number | null;
  user_created?: Directus_users | null;
  date_created?: string | null;
  user_updated?: Directus_users | null;
  date_updated?: string | null;
  name: string;
  category?: string | null;
  proficiency_level?: number | null;
  is_core_skill?: boolean | null;
  start_date?: string | null;
  projects?: unknown | null;
  accomplishments?: unknown | null;
}

export interface System_settings {
  id?: number;
  status?: string;
  sort?: number | null;
  user_created?: Directus_users | null;
  date_created?: string | null;
  user_updated?: Directus_users | null;
  date_updated?: string | null;
  // Main site title
  site_name?: string | null;
  // Professional tagline
  tagline?: string | null;
  // Primary font family
  font_primary?: string | null;
  // Secondary font family
  font_secondary?: string | null;
  // Monospace font family
  font_mono?: string | null;
  // Primary brand color
  primary_color?: string | null;
  // Light primary color
  primary_light?: string | null;
  // Dark primary color
  primary_dark?: string | null;
  // Primary background color
  background_primary?: string | null;
  // Secondary background color
  background_secondary?: string | null;
  // Primary text color
  text_primary?: string | null;
  // Secondary text color
  text_secondary?: string | null;
  // Enable site animations
  enable_animations?: boolean | null;
  // Enable dark mode toggle
  enable_dark_mode?: boolean | null;
  // Accent color for highlights
  accent_color?: string | null;
  // Success/achievement color
  success_color?: string | null;
  // Warning/attention color
  warning_color?: string | null;
}

export interface Technologies {
  id?: number;
  status?: string;
  sort?: number | null;
  user_created?: Directus_users | null;
  date_created?: string | null;
  user_updated?: Directus_users | null;
  date_updated?: string | null;
  name: string;
  category?: string | null;
  proficiency_level?: number | null;
  years_experience?: number | null;
  last_used?: string | null;
  is_current?: boolean | null;
  icon?: Directus_files | null;
  accomplishments?: unknown | null;
  projects?: unknown | null;
}

export interface Schema {
  accomplishments: Accomplishments[];
  accomplishments_projects: Accomplishments_projects[];
  accomplishments_skills: Accomplishments_skills[];
  accomplishments_technologies: Accomplishments_technologies[];
  accomplishment_variations: Accomplishment_variations[];
  certifications: Certifications[];
  companies: Companies[];
  core_values: Core_values[];
  cover_letters: Cover_letters[];
  education: Education[];
  education_accomplishments: Education_accomplishments[];
  education_related_items: Education_related_items[];
  footnotes: Footnotes[];
  identity: Identity;
  job_applications: Job_applications[];
  master_resume_system_docs: Master_resume_system_docs[];
  positions: Positions[];
  professional_summaries: Professional_summaries[];
  projects: Projects[];
  projects_companies: Projects_companies[];
  projects_files: Projects_files[];
  projects_positions: Projects_positions[];
  projects_skills: Projects_skills[];
  projects_technologies: Projects_technologies[];
  resumes: Resumes[];
  skills: Skills[];
  system_settings: System_settings[];
  technologies: Technologies[];
}

// Create the Directus client
const directusUrl = process.env.NEXT_PUBLIC_DIRECTUS_URL;
const directusToken = process.env.DIRECTUS_TOKEN;

if (!directusUrl) {
  throw new Error('NEXT_PUBLIC_DIRECTUS_URL is not defined in environment variables');
}

const baseClient = createDirectus<Schema>(directusUrl).with(rest());
export const directus = directusToken ? baseClient.with(staticToken(directusToken)) : baseClient;

// Generated helper functions

export async function getAllAccomplishments() {
  try {
    return await directus.request(readItems('accomplishments'));
  } catch (error) {
    console.error('Error fetching accomplishments:', error);
    throw error;
  }
}

export async function getAccomplishmentsById(id: string | number) {
  try {
    return await directus.request(readItem('accomplishments', id));
  } catch (error) {
    console.error('Error fetching accomplishments by id:', error);
    throw error;
  }
}

export async function getAllAccomplishments_projects() {
  try {
    return await directus.request(readItems('accomplishments_projects'));
  } catch (error) {
    console.error('Error fetching accomplishments_projects:', error);
    throw error;
  }
}

export async function getAccomplishments_projectsById(id: string | number) {
  try {
    return await directus.request(readItem('accomplishments_projects', id));
  } catch (error) {
    console.error('Error fetching accomplishments_projects by id:', error);
    throw error;
  }
}

export async function getAllAccomplishments_skills() {
  try {
    return await directus.request(readItems('accomplishments_skills'));
  } catch (error) {
    console.error('Error fetching accomplishments_skills:', error);
    throw error;
  }
}

export async function getAccomplishments_skillsById(id: string | number) {
  try {
    return await directus.request(readItem('accomplishments_skills', id));
  } catch (error) {
    console.error('Error fetching accomplishments_skills by id:', error);
    throw error;
  }
}

export async function getAllAccomplishments_technologies() {
  try {
    return await directus.request(readItems('accomplishments_technologies'));
  } catch (error) {
    console.error('Error fetching accomplishments_technologies:', error);
    throw error;
  }
}

export async function getAccomplishments_technologiesById(id: string | number) {
  try {
    return await directus.request(readItem('accomplishments_technologies', id));
  } catch (error) {
    console.error('Error fetching accomplishments_technologies by id:', error);
    throw error;
  }
}

export async function getAllAccomplishment_variations() {
  try {
    return await directus.request(readItems('accomplishment_variations'));
  } catch (error) {
    console.error('Error fetching accomplishment_variations:', error);
    throw error;
  }
}

export async function getAccomplishment_variationsById(id: string | number) {
  try {
    return await directus.request(readItem('accomplishment_variations', id));
  } catch (error) {
    console.error('Error fetching accomplishment_variations by id:', error);
    throw error;
  }
}

export async function getAllCertifications() {
  try {
    return await directus.request(readItems('certifications'));
  } catch (error) {
    console.error('Error fetching certifications:', error);
    throw error;
  }
}

export async function getCertificationsById(id: string | number) {
  try {
    return await directus.request(readItem('certifications', id));
  } catch (error) {
    console.error('Error fetching certifications by id:', error);
    throw error;
  }
}

export async function getAllCompanies() {
  try {
    return await directus.request(readItems('companies'));
  } catch (error) {
    console.error('Error fetching companies:', error);
    throw error;
  }
}

export async function getCompaniesById(id: string | number) {
  try {
    return await directus.request(readItem('companies', id));
  } catch (error) {
    console.error('Error fetching companies by id:', error);
    throw error;
  }
}

export async function getAllCore_values() {
  try {
    return await directus.request(readItems('core_values'));
  } catch (error) {
    console.error('Error fetching core_values:', error);
    throw error;
  }
}

export async function getCore_valuesById(id: string | number) {
  try {
    return await directus.request(readItem('core_values', id));
  } catch (error) {
    console.error('Error fetching core_values by id:', error);
    throw error;
  }
}

export async function getAllCover_letters() {
  try {
    return await directus.request(readItems('cover_letters'));
  } catch (error) {
    console.error('Error fetching cover_letters:', error);
    throw error;
  }
}

export async function getCover_lettersById(id: string | number) {
  try {
    return await directus.request(readItem('cover_letters', id));
  } catch (error) {
    console.error('Error fetching cover_letters by id:', error);
    throw error;
  }
}

export async function getAllEducation() {
  try {
    return await directus.request(readItems('education'));
  } catch (error) {
    console.error('Error fetching education:', error);
    throw error;
  }
}

export async function getEducationById(id: string | number) {
  try {
    return await directus.request(readItem('education', id));
  } catch (error) {
    console.error('Error fetching education by id:', error);
    throw error;
  }
}

export async function getAllEducation_accomplishments() {
  try {
    return await directus.request(readItems('education_accomplishments'));
  } catch (error) {
    console.error('Error fetching education_accomplishments:', error);
    throw error;
  }
}

export async function getEducation_accomplishmentsById(id: string | number) {
  try {
    return await directus.request(readItem('education_accomplishments', id));
  } catch (error) {
    console.error('Error fetching education_accomplishments by id:', error);
    throw error;
  }
}

export async function getAllEducation_related_items() {
  try {
    return await directus.request(readItems('education_related_items'));
  } catch (error) {
    console.error('Error fetching education_related_items:', error);
    throw error;
  }
}

export async function getEducation_related_itemsById(id: string | number) {
  try {
    return await directus.request(readItem('education_related_items', id));
  } catch (error) {
    console.error('Error fetching education_related_items by id:', error);
    throw error;
  }
}

export async function getAllFootnotes() {
  try {
    return await directus.request(readItems('footnotes'));
  } catch (error) {
    console.error('Error fetching footnotes:', error);
    throw error;
  }
}

export async function getFootnotesById(id: string | number) {
  try {
    return await directus.request(readItem('footnotes', id));
  } catch (error) {
    console.error('Error fetching footnotes by id:', error);
    throw error;
  }
}

export async function getIdentity() {
  try {
    return await directus.request(readSingleton('identity'));
  } catch (error) {
    console.error('Error fetching identity:', error);
    throw error;
  }
}

export async function getAllJob_applications() {
  try {
    return await directus.request(readItems('job_applications'));
  } catch (error) {
    console.error('Error fetching job_applications:', error);
    throw error;
  }
}

export async function getJob_applicationsById(id: string | number) {
  try {
    return await directus.request(readItem('job_applications', id));
  } catch (error) {
    console.error('Error fetching job_applications by id:', error);
    throw error;
  }
}

export async function getAllMaster_resume_system_docs() {
  try {
    return await directus.request(readItems('master_resume_system_docs'));
  } catch (error) {
    console.error('Error fetching master_resume_system_docs:', error);
    throw error;
  }
}

export async function getMaster_resume_system_docsById(id: string | number) {
  try {
    return await directus.request(readItem('master_resume_system_docs', id));
  } catch (error) {
    console.error('Error fetching master_resume_system_docs by id:', error);
    throw error;
  }
}

export async function getAllPositions() {
  try {
    return await directus.request(readItems('positions'));
  } catch (error) {
    console.error('Error fetching positions:', error);
    throw error;
  }
}

export async function getPositionsById(id: string | number) {
  try {
    return await directus.request(readItem('positions', id));
  } catch (error) {
    console.error('Error fetching positions by id:', error);
    throw error;
  }
}

export async function getAllProfessional_summaries() {
  try {
    return await directus.request(readItems('professional_summaries'));
  } catch (error) {
    console.error('Error fetching professional_summaries:', error);
    throw error;
  }
}

export async function getProfessional_summariesById(id: string | number) {
  try {
    return await directus.request(readItem('professional_summaries', id));
  } catch (error) {
    console.error('Error fetching professional_summaries by id:', error);
    throw error;
  }
}

export async function getAllProjects() {
  try {
    return await directus.request(readItems('projects'));
  } catch (error) {
    console.error('Error fetching projects:', error);
    throw error;
  }
}

export async function getProjectsById(id: string | number) {
  try {
    return await directus.request(readItem('projects', id));
  } catch (error) {
    console.error('Error fetching projects by id:', error);
    throw error;
  }
}

export async function getAllProjects_companies() {
  try {
    return await directus.request(readItems('projects_companies'));
  } catch (error) {
    console.error('Error fetching projects_companies:', error);
    throw error;
  }
}

export async function getProjects_companiesById(id: string | number) {
  try {
    return await directus.request(readItem('projects_companies', id));
  } catch (error) {
    console.error('Error fetching projects_companies by id:', error);
    throw error;
  }
}

export async function getAllProjects_files() {
  try {
    return await directus.request(readItems('projects_files'));
  } catch (error) {
    console.error('Error fetching projects_files:', error);
    throw error;
  }
}

export async function getProjects_filesById(id: string | number) {
  try {
    return await directus.request(readItem('projects_files', id));
  } catch (error) {
    console.error('Error fetching projects_files by id:', error);
    throw error;
  }
}

export async function getAllProjects_positions() {
  try {
    return await directus.request(readItems('projects_positions'));
  } catch (error) {
    console.error('Error fetching projects_positions:', error);
    throw error;
  }
}

export async function getProjects_positionsById(id: string | number) {
  try {
    return await directus.request(readItem('projects_positions', id));
  } catch (error) {
    console.error('Error fetching projects_positions by id:', error);
    throw error;
  }
}

export async function getAllProjects_skills() {
  try {
    return await directus.request(readItems('projects_skills'));
  } catch (error) {
    console.error('Error fetching projects_skills:', error);
    throw error;
  }
}

export async function getProjects_skillsById(id: string | number) {
  try {
    return await directus.request(readItem('projects_skills', id));
  } catch (error) {
    console.error('Error fetching projects_skills by id:', error);
    throw error;
  }
}

export async function getAllProjects_technologies() {
  try {
    return await directus.request(readItems('projects_technologies'));
  } catch (error) {
    console.error('Error fetching projects_technologies:', error);
    throw error;
  }
}

export async function getProjects_technologiesById(id: string | number) {
  try {
    return await directus.request(readItem('projects_technologies', id));
  } catch (error) {
    console.error('Error fetching projects_technologies by id:', error);
    throw error;
  }
}

export async function getAllResumes() {
  try {
    return await directus.request(readItems('resumes'));
  } catch (error) {
    console.error('Error fetching resumes:', error);
    throw error;
  }
}

export async function getResumesById(id: string | number) {
  try {
    return await directus.request(readItem('resumes', id));
  } catch (error) {
    console.error('Error fetching resumes by id:', error);
    throw error;
  }
}

export async function getAllSkills() {
  try {
    return await directus.request(readItems('skills'));
  } catch (error) {
    console.error('Error fetching skills:', error);
    throw error;
  }
}

export async function getSkillsById(id: string | number) {
  try {
    return await directus.request(readItem('skills', id));
  } catch (error) {
    console.error('Error fetching skills by id:', error);
    throw error;
  }
}

export async function getAllSystem_settings() {
  try {
    return await directus.request(readItems('system_settings'));
  } catch (error) {
    console.error('Error fetching system_settings:', error);
    throw error;
  }
}

export async function getSystem_settingsById(id: string | number) {
  try {
    return await directus.request(readItem('system_settings', id));
  } catch (error) {
    console.error('Error fetching system_settings by id:', error);
    throw error;
  }
}

export async function getAllTechnologies() {
  try {
    return await directus.request(readItems('technologies'));
  } catch (error) {
    console.error('Error fetching technologies:', error);
    throw error;
  }
}

export async function getTechnologiesById(id: string | number) {
  try {
    return await directus.request(readItem('technologies', id));
  } catch (error) {
    console.error('Error fetching technologies by id:', error);
    throw error;
  }
}

