/**
 * Static data layer for offline/static site generation
 * This module provides the same interface as directus.ts but reads from static JSON files
 */

// Static data imports - these will be generated by the export script
let staticData: { [key: string]: any } = {};

// Lazy load static data - use different strategies for build vs runtime
async function loadStaticData(key: string) {
  if (!staticData[key]) {
    try {
      // In browser (client-side), fetch from public URLs
      if (typeof window !== 'undefined') {
        console.log(`📊 Data source: Fetching ${key} from /data/${key}.json`);
        const response = await fetch(`/data/${key}.json`);
        if (!response.ok) {
          throw new Error(`Failed to fetch ${key}: ${response.status}`);
        }
        staticData[key] = await response.json();
      } else {
        // In Node.js (build time), use static imports
        console.log(`📊 Data source: Static import for ${key}`);
        staticData[key] = (await import(`../data/${key}.json`)).default;
      }
    } catch (error) {
      console.warn(`Static data loading failed for ${key}:`, error);
      staticData[key] = null;
    }
  }
  return staticData[key];
}

// Static versions of all the Directus functions
export async function getIdentity() {
  return await loadStaticData('identity');
}

export async function getEducation() {
  return await loadStaticData('education') || [];
}

export async function getPositions() {
  return await loadStaticData('positions') || [];
}

export async function getSkills() {
  return await loadStaticData('skills') || [];
}

export async function getProjects() {
  return await loadStaticData('projects') || [];
}

export async function getFeaturedProjects() {
  return await loadStaticData('featured-projects') || [];
}

export async function getTechnologies() {
  return await loadStaticData('technologies') || [];
}

export async function getCertifications() {
  return await loadStaticData('certifications') || [];
}

export async function getAccomplishments() {
  return await loadStaticData('accomplishments') || [];
}

export async function getFeaturedAccomplishments() {
  return await loadStaticData('featured-accomplishments') || [];
}

export async function getAccomplishmentsByType(type: string) {
  const accomplishments = await loadStaticData('accomplishments') || [];
  return accomplishments.filter((acc: any) => acc.accomplishment_type === type);
}

export async function getResumes() {
  return await loadStaticData('resumes') || [];
}

export async function getSystemSettings() {
  return await loadStaticData('system-settings');
}

export async function getFootnotes() {
  return await loadStaticData('footnotes') || [];
}

export async function getProfessionalSummaries() {
  return await loadStaticData('professional-summaries') || [];
}

export async function getCompletePortfolio() {
  const [
    identity,
    education,
    positions,
    skills,
    projects,
    certifications,
    accomplishments
  ] = await Promise.all([
    getIdentity(),
    getEducation(),
    getPositions(),
    getSkills(),
    getFeaturedProjects(),
    getCertifications(),
    getAccomplishments()
  ]);

  return {
    identity,
    education,
    positions,
    skills,
    projects,
    certifications,
    accomplishments
  };
}